######################################################################
# Automatically generated by qmake (2.01a) st srp 9 19:39:21 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += chess_board.h main_window.h ../game_logic/types.h
SOURCES += chess_board.cc main.cc main_window.cc ../game_logic/board.cc
RESOURCES += application.qrc
