######################################################################
# Automatically generated by qmake (3.0) út srp 22 16:44:09 2017
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += chess_board.h field.h main_window.h ../game_logic/types.h ../game_logic/board_controller.h
SOURCES += chess_board.cc field.cc main.cc main_window.cc ../game_logic/board_controller.cc
RESOURCES += application.qrc
